# Generated by Django 5.0.1 on 2024-05-07 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='login1',
        ),
    ]
