# Generated by Django 5.0.1 on 2024-05-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_login_login1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login1',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
