# Generated by Django 5.0.1 on 2024-05-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_login1_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login1',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
