# Generated by Django 5.0.1 on 2024-05-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_login1_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login1',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
